name: sdm
description: A new Flutter project.
 
publish_to: 'none'
 
version: 1.0.0+1
 
environment:
  sdk: '>=3.1.5 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^0.13.3
  device_info_plus: ^10.1.1
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.1
  email_validator: ^2.1.17
  geocoding: ^3.0.0
  permission_handler: ^11.0.1
  baseflow_plugin_template: ^2.1.2
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  clipboard: ^0.1.3
  google_nav_bar: ^5.0.6
  flutter_date_pickers: ^0.4.3
  loading_animation_widget: ^1.2.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  url_launcher: ^6.3.0
  geolocator: ^12.0.0
  flutter_windowmanager: ^0.2.0
  provider: ^6.0.0
  syncfusion_flutter_datagrid: ^26.1.41
  multi_select_flutter: ^4.1.3
  flutter_slidable: ^3.1.1
  #workmanager: ^0.5.2
  #flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.4
  dropdown_search: ^5.0.6
  font_awesome_flutter: ^10.0.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
 
flutter:
 
  uses-material-design: true
 
  assets:
    - images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"